apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-midpoint-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/midpoint-repository
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: midpoint-deployment
    name: midpoint-data-midpoint-repository-0
