apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-midpoint-home
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/midpoint
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: midpoint-deployment
    name: midpoint-home-midpoint-0
